# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    working_directory: ~/circleci/python
    docker:
      - image: "circleci/python:3.9.9"
    steps:
      - checkout
      - run: python3 recommend.py

  test:
    working_directory: ~/circleci/python
    docker:
      - image: "circleci/python:3.9.9"
    steps:
      -checkout
      - run: python3 tests.py

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build_and_test:
    jobs:
      - build
      - test:
        requires:
          - build
